import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Playground from "../components/Playground";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";
import { HTML5Backend } from "react-dnd-html5-backend";
import { DndProvider } from "react-dnd";
import ElementsProvider from "../contexts/ElementsProvider";
import Compile from "../components/lib/Compile";
import Navigation from "../components/navigation/Navigation";
type PageContentType = {
	title: string;
	component: JSX.Element;
	children: PageContentType;
};
const Home: NextPage = () => {
	const [pageContent, setpageContent] = useState<PageContentType[]>([]);
	return (
		<div className={styles.container}>
			<Head>
				<title>Test</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ElementsProvider>
				<div className={styles.content}>
					<DndProvider backend={HTML5Backend}>
						<Sidebar />
						<Playground />
					</DndProvider>
					<Compile />
					<Navigation />
				</div>
			</ElementsProvider>
		</div>
	);
};

export default Home;
